apiVersion: runtime.kwasm.sh/v1alpha1 
kind: Shim
metadata:
  name: slight-v1
  labels:
    app.kubernetes.io/name: slight-v1
    app.kubernetes.io/instance: slight-v1
    app.kubernetes.io/part-of: runtime-class-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: runtime-class-manager
spec:
  nodeSelector:
    slight: "true"

  fetchStrategy:
    type: anonymousHttp
    anonHttp:
      location: "https://github.com/deislabs/containerd-wasm-shims/releases/download/v0.10.0/containerd-wasm-shims-v1-slight-linux-aarch64.tar.gz"

  runtimeClass:
    name: slight-v1
    handler: slight

  rolloutStrategy:
    type: recreate
